import Vue from 'vue'
import { Button, Container, Header, Footer, Main, Menu, MenuItem, Input, Avatar, Carousel, CarouselItem, Breadcrumb, BreadcrumbItem, Image, Table, TableColumn, Dialog, Form, FormItem, Message, Tabs, TabPane, Tag, Popover } from 'element-ui'

Vue.use(Button)
Vue.use(Container)
Vue.use(Header)
Vue.use(Footer)
Vue.use(Main)
Vue.use(Menu)
Vue.use(MenuItem)
Vue.use(Input)
Vue.use(Avatar)
Vue.use(Carousel)
Vue.use(CarouselItem)
Vue.use(Breadcrumb)
Vue.use(BreadcrumbItem)
Vue.use(Image)
Vue.use(Table)
Vue.use(TableColumn)
Vue.use(Dialog)
Vue.use(Form)
Vue.use(FormItem)
Vue.use(Tabs)
Vue.use(TabPane)
Vue.use(Tag)
Vue.use(Popover)
Vue.prototype.$message = Message
